name: urban_validation
channels:
  - conda-forge
dependencies:
  - geopandas
  - pandas
  - numpy
  - shapely
  - rasterio
  - fiona
  - pyyaml
  - pyogrio
  - rtree
  - matplotlib
  - seaborn
  - google-cloud-sdk