aoi:
  path: "data/01_raw/grd-grenada/aoi/grenada-aoi.geojson" 
  id_col: "id"
  crs_out: "EPSG:4326"     
  buffer_meters: 0

overture:
  enabled: false
  provider: "aws"          
  release: "latest" 
  theme: "buildings"
  types: ["building"]
  s3_url: "s3://overturemaps-us-west-2/release/"
  s3_region: "us-west-2"

gba:
  enabled: true
  s3_url: "s3://us-west-2.opendata.source.coop/tge-labs/globalbuildingatlas-lod1/"
  s3_region: "us-west-2"
  country_iso: 'ssd'

output:
  root_dir: "/content/drive/MyDrive/Gates Foundation/Building Dataset Validation/data/"
  overwrite: false
