city: jpn-kashima
root_dir: .

crs: EPSG:32636         # UTM zone 36N

aoi_path: data/01_raw/jpn-kashima/aoi/kashima_aoi.geojson

reference_vector: data/01_raw/jpn-kashima/vector/kashima_hotosm.geojson

candidates:
- name: overture
  path: data/01_raw/jpn-kashima/vector/jpn_kashima_overture_None_building.parquet
- name: gba
  path: data/01_raw/jpn-kashima/vector/jpn_kashima_gba_None_gba_lod1.parquet

min_area_m2: 20           # filter very tiny polygons
tile_size_m: 1000         # 1 km tiles
tau_overlap: 0.5          # minimum IoU for a match
tau_buffer_m: 2.0         # positional tolerance (optional, not yet used below)
tau_boundary: 2.0         # tolerance for calculating boundary overlap